apiVersion: v1
kind: Service
metadata:
  name: {{ .values.metadata.name }}
spec:
  type: {{ .values.service.type }}
  ports:
    - port: {{ .values.service.port }}
      targetPort: 5042
      protocol: TCP
  selector:
    app: mychart
